# https://taskfile.dev/#/installation
version: '3'

silent: true

tasks:
  default:
    task -l

  0:
    desc: Stop app in docker-compose
    cmds:
      - docker-compose down

  1:
    desc: Run app and database in docker-compose
    cmds:
      - docker-compose up --build

  2:
    desc: Format code
    cmds:
      - task: tidy
      - task: fmt
      - task: lint

  tidy:
    cmds:
      - echo "Tidy..."
      - cd library && GO111MODULE=on go mod tidy && cd ..

  fmt:
    cmds:
      - echo "Fmt..."
      - gofmt -w .

  lint:
    cmds:
      - echo "Lint..."
      - golangci-lint run
  
  3:
    desc: Run testing - unit, integration, coverage
    cmds:
      - task: test-unit
      - task: test-integration
      - task: test-coverage
  
  test-unit:
    cmds:
      - env GO111MODULE=on go test --short -race -coverprofile=cover.out -v ./...

  test-integration:
    cmds:
      - newman run postman/api.postman_collection.json

  test-coverage:
    cmds:
      - env GO111MODULE=on go tool cover -func=cover.out

  4:
    desc: Benchmarking
    cmds:
      - env GO111MODULE=on go test -bench=. -cpu=8 -benchmem -cpuprofile=cpu.out -memprofile=mem.out .

  5:
    desc: Download external modules
    cmds:
      - echo "Download..."
      - GO111MODULE=on go mod download
